pipeline{
    agent any
    stages{
        stage("build"){
            steps{
                nodejs(nodeJSInstallationName: 'nodejs18.6.0') {
                    sh "npm install"
                }
            }
        }
        stage("sonar scanner"){
            steps{
                nodejs(nodeJSInstallationName: 'nodejs18.6.0') { 
                    withSonarQubeEnv('sonar'){
                        sh "npm install sonar-scanner"
                        sh "npm run sonar"
                    }
                }
            }
        }
    }
}